services:
  mysql:
    image: 'mysql:8.4.0'
    container_name: 'mysql-local-server'
    ports:
      - '13306:3306'
    volumes:
      - ./mysql-data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=my_password
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=spring_security
    labels:
      org.springframework.boot.service-connection: mysql-local-server